<section class="popup" id="popup">
	<div class="closePopup popup__close-wrap"></div>
	<div class="popup__inner">
		<button class="closePopup popup__close-icon">+</button>
		<div id="popupData">
			<h1>terms</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, nostrum in, quasi consequuntur ratione numquam voluptas quo, minus molestiae veniam ipsa quis nemo id, aliquid labore distinctio error ad laborum similique asperiores aperiam. Tempora sunt aliquid rem inventore explicabo quam alias, placeat iste officiis at quis amet quas quod repudiandae magnam soluta fugit doloremque voluptatum, odit libero error ad ab, nam consequatur. Quibusdam sunt nobis necessitatibus quia sapiente voluptatum, quae enim dignissimos quas veritatis! Neque molestiae nam provident exercitationem at libero, incidunt, aperiam quam in laboriosam inventore quaerat, blanditiis, eos quis accusantium repellat necessitatibus illum possimus? Quam non quo tempore.</p>
			<p>Adipisci excepturi iste impedit quasi similique aliquam tempore molestias cumque, corporis eligendi soluta! Obcaecati cum quaerat placeat dolorum eveniet eligendi molestiae fugit quos. Facilis cupiditate eligendi nisi ratione fugiat, vero itaque repellat obcaecati corrupti adipisci fugit animi nostrum quidem nemo magnam illum nesciunt, quo consectetur totam nihil harum ipsum repudiandae esse! Amet debitis veritatis deleniti recusandae voluptates nemo dolor omnis quas dolore maxime commodi accusantium ut excepturi aliquam totam, accusamus ipsa vitae repellat unde ratione ad ab, earum tempore. Earum maiores totam nulla quis, nostrum similique facere maxime vel numquam tempora, delectus hic nobis molestiae atque repudiandae error. Magni, aliquid.</p>
			<p>Excepturi quam, natus esse voluptate optio id soluta, eveniet dolorum dolor earum eaque enim accusamus omnis laborum ipsa iusto nostrum quia recusandae alias est qui debitis nulla veniam iure! Vitae dolor rem inventore! Provident autem necessitatibus corrupti consectetur nulla quod adipisci obcaecati, sit vitae quidem incidunt sunt aliquam, aperiam perferendis voluptas natus repellat corporis quaerat a id error officiis. Quas voluptatibus consectetur corporis molestiae quaerat aperiam, debitis minima culpa animi labore voluptatum nisi adipisci distinctio autem voluptatem possimus, vero, earum dolores id similique quam aspernatur nulla! Odit repudiandae id minus culpa dignissimos. Optio repudiandae, quia corrupti obcaecati vel aspernatur neque.</p>
			<p>Consectetur et laudantium unde fuga tempora adipisci dolorem, ex magni veniam labore dicta voluptatibus in numquam architecto optio quaerat repellat ullam enim cupiditate delectus veritatis, maxime officiis voluptas magnam! Hic corporis facere, velit et maiores quaerat, iste, nam laborum accusantium pariatur illo itaque dolorem numquam earum. Pariatur, voluptatum, ratione. Sit labore temporibus reiciendis officia alias facilis. Minus eius quam mollitia qui, explicabo modi hic ad laborum illum ipsam provident, laboriosam, ullam beatae ea harum. Sed soluta aperiam iure suscipit facilis quos similique et sapiente deleniti. Quia nesciunt illum nemo, aspernatur ad veritatis rem, ullam quos ratione obcaecati quidem aut enim.</p>
			<p>Ullam iusto commodi, neque vel nisi officiis non. Dignissimos libero reiciendis, at iure recusandae molestiae ipsa laboriosam. Accusamus quasi soluta saepe autem iure deleniti minima, vero maiores quibusdam laudantium aliquid explicabo labore, voluptatem, omnis sit dignissimos. Omnis, placeat! Porro quaerat ipsa sapiente, nostrum id ipsam quibusdam explicabo incidunt libero dolores eos architecto quas enim, harum magnam ipsum aspernatur, laborum quisquam corporis. Eius libero id in placeat iusto amet laudantium consequatur iste distinctio quis, porro et enim qui nulla labore at ad perferendis quia nobis. Pariatur sit aperiam quod architecto, a tempore repellat. Voluptate, aperiam sit quos! Numquam soluta possimus excepturi.</p>
			<p>Totam officia eius, laudantium fugit placeat accusamus aspernatur accusantium omnis quibusdam. Suscipit blanditiis at numquam, quae optio quis facilis, nostrum eius ad repellendus asperiores maiores odit animi. Officia consectetur odit eaque cum harum, id architecto reprehenderit vitae magnam at tempore. Obcaecati neque officiis, odit nobis labore maxime odio pariatur quod expedita incidunt eligendi placeat sit inventore eveniet vel doloribus et excepturi rerum autem adipisci! Ut impedit quia nisi, eligendi sunt delectus, aliquid asperiores magnam, saepe atque magni officia illo dolorum nesciunt. Amet ab magnam, nemo omnis rerum explicabo magni autem nesciunt, consequuntur dicta dolore voluptatum accusantium aspernatur nihil, eos unde?</p>
			<p>Magni explicabo totam ipsa autem est in adipisci eligendi, accusantium deleniti repudiandae. Rem id nostrum illo labore corporis enim laborum. Quia ducimus dignissimos porro cupiditate autem asperiores ex, nihil atque labore ut, possimus velit neque quibusdam consequatur praesentium ipsa. Voluptatibus numquam ipsa eligendi aut incidunt impedit, quibusdam vero fuga placeat labore voluptas et reiciendis consectetur, quia error expedita quaerat eos quam quo dolorem quidem natus sequi? Atque sapiente quasi, ducimus quis explicabo iusto nisi maxime? Velit sint fuga consequuntur doloribus ad iusto laboriosam alias ullam optio quia neque fugit aut, necessitatibus accusantium nam assumenda repellat! Veritatis temporibus aperiam, et voluptate.</p>
			<p>Neque esse molestiae odit quaerat, nihil quod maxime dolor perferendis consequatur totam tempore error sapiente possimus alias commodi atque, nemo beatae officia a dolorum excepturi quae officiis. Illo nihil repudiandae error est quos distinctio facere sit similique nobis molestias minima, fuga amet dolorem eius dignissimos quasi quae enim veniam. Reprehenderit voluptate, laboriosam saepe obcaecati a, accusantium excepturi eum, pariatur unde doloremque alias eligendi. Quidem odit nostrum repudiandae, cupiditate recusandae voluptatum officiis. Veritatis laboriosam molestiae in cumque nostrum voluptatum exercitationem facilis, asperiores minus nulla sit, natus porro voluptatibus, tempore ad odio. Facere expedita commodi, accusantium, sed repudiandae velit autem totam? Rerum!</p>
			<p>Assumenda dignissimos voluptatum modi corrupti nostrum numquam, eius amet tempora libero delectus illo reiciendis quia rem saepe ullam fugit aut unde consequuntur maiores ducimus ratione quos commodi. Vel odio obcaecati, quis, quisquam nostrum, libero inventore, iure praesentium repudiandae asperiores temporibus. Vero eius, adipisci. Ea sapiente ex debitis deleniti modi, aperiam. Officiis recusandae vitae neque repellat ratione, vel esse quos explicabo nobis amet, magnam quas soluta! Illo sint, consequatur fugit minima magni quaerat atque neque sed praesentium, quasi nisi excepturi repellat eius odio eligendi. Veritatis nihil enim, beatae assumenda, eaque iusto quasi quos dolorum aspernatur nisi quia dolore laudantium facere earum.</p>
			<p>Laudantium assumenda architecto id atque repudiandae, non explicabo, magni fugit, facilis nulla odit! Ab quod molestiae rem nostrum perferendis ipsa nam doloribus dolorem explicabo provident accusamus atque ratione cupiditate, nulla magni aperiam facilis facere iusto quaerat illum alias odit. Maxime laborum illo eaque, vel, libero voluptatibus, consequuntur numquam perspiciatis magnam aliquid voluptate quas alias quod voluptatem dolores! Atque deleniti aliquam, commodi quas sequi officiis voluptates nesciunt eum laboriosam, omnis illo provident fugiat. Eos architecto quia dignissimos fugit aut labore dolore assumenda nesciunt explicabo, aliquid vero libero eius nostrum. Est, id nobis! Unde sequi minus quaerat non beatae, dicta nihil excepturi.</p>
		</div>
	</div>
</section>